[package]
name = "minigrep"
version = "0.1.0"
authors = ["Kishor Paroi <Kishor.ruet.cse@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kishorkumarparoi/rust-learning/minigrep"
[dependencies]
